server:
  port: 8080

spring:
  application:
    name: ms-gateway

# Rota para o Microservico de Cliente
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rota-cliente
              uri: http://localhost:8081
              predicates:
                - Path=/cliente/**

            - id: rota-conta
              uri: http://localhost:8082
              predicates:
                - Path=/conta/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    com.lucas.ms_gateway: DEBUG