spring.application.name=ms-usuario

server.port=8081

#Banco h2
spring.datasource.url=jdbc:h2:mem:clientedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Lucas
spring.datasource.password=
spring.h2.console.enabled=true

#jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

# Hateoas: faz os links apontarem para a porta 8080 do gateway
server.forward-headers-strategy=framework

# Ativa o script da data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true